apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "weather.name" . }}
  labels: {{ include "weather.labels" . | nindent 4 }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "weather.name" . }}
                port:
                  name: http