apiVersion: v1
kind: Service
metadata:
  name: {{ template "weather.name" . }}
  labels: {{ include "weather.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{ include "weather.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http